### PR TITLE
new yaml_dump_stream() native jsonnet function

### PR DESCRIPTION
**Pull request by chaudyg**
Add a new yaml_dump_stream native jsonnet function
Similar to https://github.com/deepmind/kapitan/issues/404 but with dump instead of load.

## Proposed Changes
- Add a new yaml_dump_stream native jsonnet function able to dump a list of json objects into a yaml stream

### CODE REVIEW

**Comment by ramaro** [comment]
@chaudyg thanks for this. How different is it from Jsonnet's `std.manifestYamlStream()`?

**Comment by chaudyg** [comment]
@googlebot I signed it!

**Comment by chaudyg** [comment]
It's pretty much the same. `std.manifestYamlStream()` is just asefully slow (x5).

**Comment by ramaro** [comment]
@chaudyg great! Can you add it to the docs as well? Thanks

**Comment by uberspot** [comment]
Besides adding the new func to docs/compile.md, I think you used a different email for your git commit than the one you used to sign the CLA. You might have to either change the author of your commit and force-push to this branch again or sign the CLA with the other email you used here. :) 
The rest lgtm.

**Comment by chaudyg** [comment]
@ramaro  @uberspot Thanks for the feedback. Implemented the changes. Let me know if that works for you. Cheers!

**Pull request merged**
