### PR TITLE
Fix reveal from ref file bug

### PR DESCRIPTION
**Pull request by AlphaRoy14**
Fixes issue #604 

## Proposed Changes

  - Fix reveal from ref file bug
  - Add test cases

### CODE REVIEW

**Review by uberspot — APPROVED** [review]
Nice :)

**Comment by uberspot** [comment]
Python black linter failed. Could you run `make format_codestyle`?

**Comment by AlphaRoy14** [comment]
> Python black linter failed. Could you run `make format_codestyle`?

I did, and I tried it once again now but there isn't any change in formatting.

**Comment by uberspot** [comment]
> > Python black linter failed. Could you run `make format_codestyle`?
> 
> I did, and I tried it once again now but there isn't any change in formatting.

No worries. I merged for now and I'll fix it separately. :+1: 
It could be that you have to `pip3 install --upgrade --user black` to get the latest version.

**Comment by AlphaRoy14** [comment]
Ah yes, it reformatted after upgrading. Thanks! :D

**Pull request merged**
