### PR TITLE
HTML anchors are case-sensitive

### PR DESCRIPTION
**Pull request by jhermann**

### CODE REVIEW

**Comment by ramaro** [comment]
Well spotted @jhermann thank you!

**Comment by jhermann** [comment]
Sorry, won't enter our internal CLA workflow for changing case of 3 letters.

**Comment by ramaro** [comment]
Fair enough, we'll change it. Thanks again @jhermann

**Comment by ademariag** [comment]
Thank you @jhermann I have made the change for you.

**Pull request closed without merging**
