### PR TITLE
Update reclass submodule with latest upstream changes

### PR DESCRIPTION
**Pull request by taharah**
Signed-off-by: Trevor Wood <Trevor.G.Wood@gmail.com>

## Proposed Changes

* Updates the reclass submodule to point to the upstream `develop` branch and pulls in the latest changes.

### CODE REVIEW

**Comment by taharah** [comment]
Upstream PR for the fix: https://github.com/salt-formulas/reclass/pull/87

**Comment by uberspot** [comment]
Thanks a lot for the regression fix in reclass @taharah ! Nice work. :) 
Unfortunately we can't accept the .gitmodules change as it points to a private repo, but I'll gladly update reclass once your fix is merged!

**Comment by taharah** [comment]
Makes sense! I'll update the PR once the upstream change has been merged.

**Comment by uberspot** [comment]
Just to give an update on this, we ended up forking the salt-formulas/reclass dependency to our own repo so that we can patch the fix above. That is now being used in kapitan 0.27.3 and after. :) 
Closing as fixed

**Pull request closed without merging**
