### PR TITLE
[WIP] Expand init

### PR DESCRIPTION
**Pull request by vaibhavk**
Fixes issue #215 

## Proposed Changes

- [x] parameterizable target files

- [X] parameterizable class files

- [X] parameterizable components (jinja2, kadet, jsonnet)

### CODE REVIEW

**Comment by vaibhavk** [comment]
@uberspot I'm not using a gmail account, count that be the reason for this comment?
> We found a Contributor License Agreement for you (the sender of this pull request), but were unable to find agreements for all the commit author(s) or Co-authors. If you authored these, maybe you used a different email address in the git commits than was used to sign the CLA ([login here](https://cla.developers.google.com/) to double check)?

**Comment by harsh-98** [comment]
@vaibhavk It is related to you agreeing that your code can be used without any restrictions in any way google finds necessary and other things mentioned in licenses. You just have to agree to it once.

**Comment by vaibhavk** [comment]
> @vaibhavk It is related to you agreeing that your code can be used without any restrictions in any way google finds necessary and other things mentioned in licenses. You just have to agree to it once.
Ah I see, but I signed it like 3 days ago, thanks for the support.
Can try by switching e-mail address once.

**Comment by adrianchifor** [comment]
@vaibhavk You commited twice as `Ubuntu`

**Comment by vaibhavk** [comment]
@adrianchifor  Now I have made several commits as vaibhavk, should I close this PR and start with a new one?
> @vaibhavk You commited twice as `Ubuntu`

**Comment by adrianchifor** [comment]
Yep, otherwise the `cla/google` verification will not pass.

**Pull request closed without merging**
