### PR TITLE
"inventory --pattern" requires "--target_name" to be specified

### PR DESCRIPTION
**Pull request by gburiola**

### CODE REVIEW

**Comment by gburiola** [comment]
```
$ ./kapitan inventory --pattern parameters.target_name
usage: kapitan [-h] [--version] {eval,compile,inventory,searchvar,secrets} ...
kapitan: error: --pattern requires --target_name
```

**Comment by ramaro** [comment]
How about we make it filter all targets when -t is not passed instead?

**Comment by adrianchifor** [comment]
Will do

**Comment by ramaro** [comment]
Merging for now. We can improve later

**Pull request merged**
